Repository UltraStar-Deluxe/USDX, pull requests merged in 2023-03, with the labels that each got.

#562 Use LetterBox aspect ratio instead of Crop. Toggle video aspect ratio in SingScreen via ’A’.
  src/media/UVideo.pas
  src/screens/UScreenEditSub.pas
  src/screens/UScreenJukebox.pas
  src/screens/controllers/UScreenSingController.pas
Labels: enhancement

#627 Refactor singdraw
  src/base/UDraw.pas
Labels: help wanted, testers needed

#618 make the timebar display correctly when using START values
  src/base/UDraw.pas
  src/screens/views/UScreenSingView.pas
Labels: enhancement, testers needed
